import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";

// Initialize S3 Client
// Note: In a production environment, it is recommended to use presigned URLs 
// generated by a backend to avoid exposing credentials in the frontend.
const s3Client = new S3Client({
  region: import.meta.env.VITE_AWS_REGION,
  credentials: {
    accessKeyId: import.meta.env.VITE_AWS_ACCESS_KEY_ID,
    secretAccessKey: import.meta.env.VITE_AWS_SECRET_ACCESS_KEY,
  },
});

export const uploadImageToS3 = async (file) => {
  const fileName = `cars/${Date.now()}_${file.name.replace(/\s/g, '_')}`;
  
  const params = {
    Bucket: import.meta.env.VITE_AWS_BUCKET_NAME,
    Key: fileName,
    Body: file,
    ContentType: file.type,
    // ACL: 'public-read', // Uncomment if bucket is not public by default and you want it to be
  };

  try {
    const command = new PutObjectCommand(params);
    await s3Client.send(command);
    
    // Construct the public URL (assuming standard S3 URL format)
    const url = `https://${import.meta.env.VITE_AWS_BUCKET_NAME}.s3.${import.meta.env.VITE_AWS_REGION}.amazonaws.com/${fileName}`;
    return url;
  } catch (error) {
    console.error("S3 Upload Error:", error);
    throw new Error("Failed to upload image to S3");
  }
};
